### ISSUE TITLE
Positions while RX

### ISSUE THREAD

**Issue by dk8hc** [oe3cjb/TTGO-T-Beam-LoRa-APRS#13]
Hi, is it possible to decode the received coordinates and show them in the displaytext? ![IMG_20210131_001503.jpg](https://user-images.githubusercontent.com/77748633/106370380-bda6da80-6359-11eb-998d-5b5b14ec29dc.jpg)

**Comment by oe3cjb** [comment]
I've once written a LoRa Decoder (https://github.com/oe3cjb/LoRa_Receiver_OLED), but never planned to implement into the code, because a lot of capabilities have to be considered: how long should a package be displayed? Only the last one? or a list of last 5 or so? 
This also woul dmean lot of work I currently do not have the time for.
