### ISSUE TITLE
Tracker mode setting does not work...

### ISSUE THREAD

**Issue by cyberknol** [oe3cjb/TTGO-T-Beam-LoRa-APRS#14]
Hi, When I set Tracker mode setting to 1, 2 or 3 it boots up in mode Tracker (=0).  Set #define DONT_USE_FLASH_MEMORY on or off has no effect. It boots in Tracker mode (no WX). Only when I push the middle button on my V1 T-Beam (no Oled) for 10 Seconds I see it switching (in the terminal screen) to WX-Tracker and WX report becomes visible in APRS.fi. But when I restart the T-Beam by plug in the power, it boots up in Tracker mode (no WX).

(PA1SDB-7 iGate - PA1SDB-9 mobile - PA1SDB-8 WX)

73s Peter

**Comment by oe3cjb** [comment]
Hi, thank for bringing this to my attention! Your are now the second who has this effect. I've already started the investigations and my guess is, that there is something wrong with the type of variables written to the flash memory. Needs some modifications and will take few weeks to solve. Please have a little patience. 73 oe3cjb

**Comment by oe3cjb** [comment]
I've created a new branch "trackermode_correction" with a quick trial to solve this issue - please comment your results - tks es 73

**Comment by cyberknol** [comment]
This weekend I'll try again. Tnx.

**Comment by cyberknol** [comment]
Still no luck here. Same results...


--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at http://bit.ly/pio-monitor-filters
--- Miniterm on COM4  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
LoRa-APRS / Init / AXP192 Begin PASS
LoRa-APRS / Init / Display OK! / PRESS 3sec for config
LoRa-APRS / Call=PA1SDB-9 / WX-Call=PA1SDB-8 / TxSymbol=>
LoRa-APRS / Init / Mode / TRACKER
LoRa-APRS / Init / RF95 OK!
LoRa-APRS / Init / GPS Serial OK!
LoRa-APRS / Init / Waiting for GPS
LoRa-APRS / Init / Data from GPS OK!
LoRa-APRS / Init / ADC OK! / BAT: 0.1
LoRa-APRS / Init / Temp OK! Temp=25.60 Hum=21.00
LoRa-APRS / Init / FINISHED OK! / =:-)
outString=PA1SDB-9>APRS:!/3Za'P9]g>!.HVoice QRV via PI2NOG repeater @430.325MHz (Lora APRS @433.775MHz)
((TX)) / LAT: 53.13687 / LON: 7.02904 / SPD: 3.5 / CRS: 0.0 / SAT: 7 / BAT: 0.0 / TEMP: 25.6 / HUM: 21.0
outString=PA1SDB-9>APRS:!/3ZatP9]a>!#HVoice QRV via PI2NOG repeater @430.325MHz (Lora APRS @433.775MHz)
((TX)) / LAT: 53.13666 / LON: 7.02901 / SPD: 0.5 / CRS: 0.0 / SAT: 9 / BAT: 0.0 / TEMP: 25.6 / HUM: 22.2



Only when I push the middle button for > 10 seconds it shows

LoRa-APRS / New Mode / WX-TRACKER

After reboot, it starts in Tracker mode. Does not matter if I uncomment or comment that "Use Flash" line.

73s Peter de PA1SDB

**Comment by oe3cjb** [comment]
Dear Peter,just to be sure, but you used the new branch trackermode_correction?=> https://github.com/oe3cjb/TTGO-T-Beam-LoRa-APRS/tree/trackermode_correctionIf yes I will further investigate the root cause for this strange behaviour73 de Christian OE3CJBVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: cyberknol <notifications@github.com> Datum: 14.02.21  10:24  (GMT+01:00) An: oe3cjb/TTGO-T-Beam-LoRa-APRS <TTGO-T-Beam-LoRa-APRS@noreply.github.com> Cc: oe3cjb <oe3cjb@gmail.com>, Comment <comment@noreply.github.com> Betreff: Re: [oe3cjb/TTGO-T-Beam-LoRa-APRS] Tracker mode setting does not work... (#14) 
Still no luck here. Same results...
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at http://bit.ly/pio-monitor-filters
--- Miniterm on COM4  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun  8 2016 00:22:57
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
LoRa-APRS / Init / AXP192 Begin PASS
LoRa-APRS / Init / Display OK! / PRESS 3sec for config
LoRa-APRS / Call=PA1SDB-9 / WX-Call=PA1SDB-8 / TxSymbol=>
LoRa-APRS / Init / Mode / TRACKER
LoRa-APRS / Init / RF95 OK!
LoRa-APRS / Init / GPS Serial OK!
LoRa-APRS / Init / Waiting for GPS
LoRa-APRS / Init / Data from GPS OK!
LoRa-APRS / Init / ADC OK! / BAT: 0.1
LoRa-APRS / Init / Temp OK! Temp=25.60 Hum=21.00
LoRa-APRS / Init / FINISHED OK! / =:-)
outString=PA1SDB-9>APRS:!/3Za'P9]g>!.HVoice QRV via PI2NOG repeater @430.325MHz (Lora APRS @433.775MHz)
((TX)) / LAT: 53.13687 / LON: 7.02904 / SPD: 3.5 / CRS: 0.0 / SAT: 7 / BAT: 0.0 / TEMP: 25.6 / HUM: 21.0
outString=PA1SDB-9>APRS:!/3ZatP9]a>!#HVoice QRV via PI2NOG repeater @430.325MHz (Lora APRS @433.775MHz)
((TX)) / LAT: 53.13666 / LON: 7.02901 / SPD: 0.5 / CRS: 0.0 / SAT: 9 / BAT: 0.0 / TEMP: 25.6 / HUM: 22.2
Only when I push the middle button for > 10 seconds it shows
LoRa-APRS / New Mode / WX-TRACKER
After reboot, it starts in Tracker mode. Does not matter if I uncomment or comment that "Use Flash" line.
73s Peter de PA1SDB

**Comment by cyberknol** [comment]
Oops... I did just download the basic file at github. Sorry, have patience.
I'll try again tomorrow...

Peter.

Op zo 14 feb. 2021 19:05 schreef oe3cjb <notifications@github.com>:

**Comment by cyberknol** [comment]
Hello,
I did now realy downloaded "TTGO-T-Beam-LoRa-APRS-trackermode_correction.zip". Unfortunately still in Tracker mode after a boot while I set #define TRACKERMODE 1.

Same results with #define TRACKERMODE 2.

I did uncomment "#define DONT_USE_FLASH_MEMORY". 

I did hit Clean code button and Erase flash before compiling and uploading to be sure. 

That's what I observe.

Peter

**Comment by oe3cjb** [comment]
Hello Peter,thank you for your efforts and testing! I will analyze further what could be wrong. Please stay tuned...73Christian Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: cyberknol <notifications@github.com> Datum: 15.02.21  19:07  (GMT+01:00) An: oe3cjb/TTGO-T-Beam-LoRa-APRS <TTGO-T-Beam-LoRa-APRS@noreply.github.com> Cc: oe3cjb <oe3cjb@gmail.com>, Comment <comment@noreply.github.com> Betreff: Re: [oe3cjb/TTGO-T-Beam-LoRa-APRS] Tracker mode setting does not work... (#14) 
Hello,
I did now realy downloaded "TTGO-T-Beam-LoRa-APRS-trackermode_correction.zip". Unfortunately still in Tracker mode after a boot while I set #define TRACKERMODE 1.
Same results with #define TRACKERMODE 2.
I did uncomment "#define DONT_USE_FLASH_MEMORY".
I did hit Clean code button and Erase flash before compiling and uploading to be sure.
That's what I observe.
Peter

**Comment by oe3cjb** [comment]
Hello Peter,

 

bug identified and cancelled – the code should now also use the correct trackermode (the reason was one additional line setting trackermode always to “tracker”)

 

73

Christian oe3cjb

 

Von: Christian OE3CJB Bauer <oe3cjb@gmail.com> 
Gesendet: Montag, 15. Februar 2021 21:38
An: oe3cjb/TTGO-T-Beam-LoRa-APRS <reply@reply.github.com>; oe3cjb/TTGO-T-Beam-LoRa-APRS <TTGO-T-Beam-LoRa-APRS@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Betreff: Re: [oe3cjb/TTGO-T-Beam-LoRa-APRS] Tracker mode setting does not work... (#14)

 

Hello Peter,

thank you for your efforts and testing! I will analyze further what could be wrong. Please stay tuned...

73

Christian 

 

 

 

Von meinem/meiner Galaxy gesendet

 

 

-------- Ursprüngliche Nachricht --------

Von: cyberknol <notifications@github.com <mailto:notifications@github.com> > 

Datum: 15.02.21 19:07 (GMT+01:00) 

An: oe3cjb/TTGO-T-Beam-LoRa-APRS <TTGO-T-Beam-LoRa-APRS@noreply.github.com <mailto:TTGO-T-Beam-LoRa-APRS@noreply.github.com> > 

Cc: oe3cjb <oe3cjb@gmail.com <mailto:oe3cjb@gmail.com> >, Comment <comment@noreply.github.com <mailto:comment@noreply.github.com> > 

Betreff: Re: [oe3cjb/TTGO-T-Beam-LoRa-APRS] Tracker mode setting does not work... (#14) 

 

Hello,
I did now realy downloaded "TTGO-T-Beam-LoRa-APRS-trackermode_correction.zip". Unfortunately still in Tracker mode after a boot while I set #define TRACKERMODE 1.

Same results with #define TRACKERMODE 2.

I did uncomment "#define DONT_USE_FLASH_MEMORY".

I did hit Clean code button and Erase flash before compiling and uploading to be sure.

That's what I observe.

Peter

**Comment by cyberknol** [comment]
LoRa-APRS / Init / Mode / WX & TRACKER

Yessss....  It works now well !  After power on it starts in WX and Tracker mode 

(#define TRACKERMODE 1 and uncommeted #define DONT_USE_FLASH_MEMORY)

Looks fine now, Tnx !

73's Peter de PA1SDB
